### ISSUE TITLE
Feature request: move window by X pixels in Y direction

### ISSUE THREAD

**Issue by yusifsalam** [rxhanson/Rectangle#164] opened 2020-05-29 10:42 UTC
Currently Rectangle has Move Left/Right/Up/Down but those options pin the window to the middle of the selected direction border. Moving a window by an arbitrary number of pixels in each direction would allow for greater control over the window position on the screen, sort of mimicking window dragging but using keyboard only.

**Comment by rxhanson** [comment] 2020-05-29 13:17
Duplicate of https://github.com/rxhanson/Rectangle/issues/143

**Closed by rxhanson** 2020-05-29 13:17 UTC
