### ISSUE TITLE
No snapping when selecting a different window from the same application

### ISSUE THREAD

**Issue by eatingcereall** [rxhanson/Rectangle#178] opened 2020-06-23 15:10 UTC
macOS version: 10.15.5
Rectangle version: 0.3 (35)

When you have two windows from the same application open on a single desktop, and one of the windows is selected/at the forefront, then select the other window from any part of the toolbar that isn't the name, it won't respond to it/won't snap or so UI. Once you let go and reselect it, it will function properly.

Tried it on Preview, Safari and Microsoft Word.

There are rare occasions this doesn't happen from me and it functions properly (however I am not sure what triggers it to function properly).

First video shows it on Preview, also showing how it will work properly when the name section of the window is selected. Second video shows it on Safari.

https://youtu.be/x0WR8mmSlTc 

https://youtu.be/bPnijvMYEFo

**Comment by rxhanson** [comment] 2020-06-23 21:33
Thanks for the videos. I was able to reproduce this, so I should be able to figure out a solution to it. I'll slate it for the next release.

**Comment by chitalian** [comment] 2020-06-24 18:44
I had the same issue. It seems to be a problem with NSEvent messing up. 
https://developer.apple.com/documentation/appkit/nsevent/1529068-locationinwindow

A really hacky work around is to just update the frontWindowId on every leftMouseDragged event. 

```swift
        case .leftMouseDragged:
//            if frontmostWindowId == nil {
                frontmostWindowId = frontmostWindow?.getIdentifier()
//            }
```

Not a fan of this solution, but not sure if there is a more elegant solution. I can file an issue with Apple if you want @rxhanson?

**Comment by rxhanson** [comment] 2020-06-24 19:19
@chitalian I was guessing that it probably had to do with getting the window identifier (I haven't had a chance to debug through it), but I think there will be a way to properly get or update the window identifier in an elegant way. It's an expensive enough call that we want to use it sparingly. This is isn't an Apple bug (although thanks for the offer to file a bug). Rectangle uses the accessibility API to move/resize windows, but that API does not have unique identification for windows, and Rectangle needs unique identifiers to manage the window history. In order to uniquely identify the windows and correlate when using the accessibility API, Rectangle will use the Carbon API and look through all of the windows. This happens in `that getIdentifier()` call in `AccessibilityElement`. It's not pretty but it's the only way I'm aware that this can be done, and the bug might be in that method.

**Comment by rxhanson** [comment] 2020-06-27 22:09
This should be fixed in 
https://github.com/rxhanson/Rectangle/releases/tag/v0.31

Please try it out and let me know.

**Comment by eatingcereall** [comment] 2020-06-28 19:29
It works beautifully, thank you for your great support for this wonderful application.

**Closed** 2020-07-01 07:15 UTC
Labels: bug
