### ISSUE TITLE
Reflow Todo is not anchored properly @ top of display.

### ISSUE THREAD

**Issue by diosmiodio** [rxhanson/Rectangle#836] opened 2022-06-27 17:12 UTC
This happens with any app, but reflowing to-do leaves around a 85px gap from the top of the menu-bar and the app on an M1 MacBook Pro.

macOS version: 12.4
macOS Model: Apple M1 Max Macbook Pro 16''
Rectangle version: v0.56 (62)
Logs:
```
2022-06-27T10:04:10-07:00: AX sizing proposed: (1328.0, 1117.0), result: (1728.0, 1117.0)
2022-06-27T10:04:10-07:00: AX position proposed: (0.0, 0.0), result: (0.0, 0.0)
2022-06-27T10:04:10-07:00: AX sizing proposed: (1328.0, 1117.0), result: (1728.0, 1117.0)
2022-06-27T10:04:10-07:00: AX sizing proposed: (400.0, 996.0), result: (400.0, 994.0)
2022-06-27T10:04:10-07:00: AX position proposed: (1328.0, 121.0), result: (1328.0, 121.0)
2022-06-27T10:04:10-07:00: AX sizing proposed: (400.0, 996.0), result: (400.0, 994.0)
```
Video:
https://user-images.githubusercontent.com/16040181/175997526-6d5e3462-8b1d-4585-bb65-e2420e83af43.mov

**Comment by rxhanson** [comment] 2022-06-27 18:24
Thanks for reporting. I cannot reproduce this, even with Things as the Todo app. 

1. Is this as large as your Things window will go, even if you try to manually resize it larger? 
2. Does it work properly with something like "Reminders" as your Todo app?
3. Do you have multiple displays?

**Comment by diosmiodio** [comment] 2022-06-27 20:32
Of course, it's my pleasure. Thanks for taking a look & providing this utility in the first place 😊

1. My things window behaves as normal, I can resize it & shrink it as much I want. 400px wide is the smallest it goes & is what I have rectangle config set to for the todo app. [Here is another video](https://user-images.githubusercontent.com/16040181/176029417-da3227e0-b935-46a3-8673-6751839e7cdf.mov) of the behavior with the things window being wide at first. **Rectangle seems to be properly setting the width**, and height stays the same, it just seems to nudge it ~85px down (got the measurement using snipping tool, not sure if 85px is the absolute measurement)
2. No, it still exhibits the [same behavior](https://user-images.githubusercontent.com/16040181/176029715-6b032a66-192a-4f2f-bb94-8acb9cebef00.mov) with the reminders app and any other app I make the "Todo App"
3. Nope, all of these videos are happening with a single display. I can test later to see if it exhibits the same behavior with multiple though if that would be helpful!

**Comment by rxhanson** [comment] 2022-06-28 02:42
Got it, fix is in and I think I'll have a release out sometime this week.

**Comment by diosmiodio** [comment] 2022-08-15 16:55
Sorry for the latent reply, but thank you SO much for fixing this so quickly. You seriously rock 🤘

**Closed** 2022-08-16 00:07 UTC
Labels: bug
