### ISSUE TITLE
Move to next display does not work with apps in full screen

### ISSUE THREAD

**Issue by dahosek** [rxhanson/Rectangle#585] opened 2021-09-29 00:44 UTC
- [ ] This is a new bug that hasn't been documented in a closed issue or in the Readme.

macOS version: 11.6
Rectangle version: 0.48
Logs if applicable (In Rectangle menu, hold option, "View Logging..."): 

```
2021-09-28T19:43:00-05:00: AX sizing proposed: (2048.0, 1255.0), result: (3840.0, 1600.0)
2021-09-28T19:43:00-05:00: AX position proposed: (3840.0, 505.0), result: (0.0, 0.0)
2021-09-28T19:43:00-05:00: AX sizing proposed: (2048.0, 1255.0), result: (3840.0, 1600.0)
2021-09-28T19:43:00-05:00: AX sizing proposed: (3840.0, 1600.0), result: (3840.0, 1600.0)
2021-09-28T19:43:00-05:00: AX position proposed: (3840.0, 505.0), result: (0.0, 0.0)
2021-09-28T19:43:00-05:00: AX sizing proposed: (3840.0, 1600.0), result: (3840.0, 1600.0)
2021-09-28T19:43:00-05:00: nextDisplay | display: (3840.0, -160.0, 2048.0, 1255.0), calculatedRect: (3840.0, 505.0, 2048.0, 1255.0), resultRect: (0.0, 0.0, 3840.0, 1600.0), srcScreen: LG ULTRAWIDE, destScreen: Built-in Retina Display, resultScreen: LG ULTRAWIDE
```

```
2021-09-28T19:43:54-05:00: AX sizing proposed: (2048.0, 1280.0), result: (2048.0, 1280.0)
2021-09-28T19:43:54-05:00: AX position proposed: (896.0, 172.0), result: (3840.0, 480.0)
2021-09-28T19:43:54-05:00: AX sizing proposed: (2048.0, 1280.0), result: (2048.0, 1280.0)
2021-09-28T19:43:54-05:00: AX sizing proposed: (2048.0, 1280.0), result: (2048.0, 1280.0)
2021-09-28T19:43:54-05:00: AX position proposed: (1792.0, 320.0), result: (3840.0, 480.0)
2021-09-28T19:43:54-05:00: AX sizing proposed: (2048.0, 1280.0), result: (2048.0, 1280.0)
2021-09-28T19:43:54-05:00: previousDisplay | display: (0.0, 0.0, 3840.0, 1575.0), calculatedRect: (896.0, 172.0, 2048.0, 1280.0), resultRect: (3840.0, 480.0, 2048.0, 1280.0), srcScreen: Built-in Retina Display, destScreen: LG ULTRAWIDE, resultScreen: Built-in Retina Display
```

**Comment by rxhanson** [comment] 2021-09-29 00:59
Duplicate of https://github.com/rxhanson/Rectangle/discussions/551

**Closed by rxhanson** 2021-09-29 00:59 UTC
Labels: bug
