### ISSUE TITLE
Next/Previous display is broken in v0.4

### ISSUE THREAD

**Issue by stgarf** [rxhanson/Rectangle#11] opened 2019-09-01 23:00 UTC
Hey Ryan (@rxhanson),

Rectangle's been working great until I powered up an eGPU and connected my external displays to it. From this point, I can no longer shift windows between displays `({Next,Previous} Display).`

Inside of each individual display, however, I can do all the usual stuff if I drag the window over to that particular display: `half`, `2/3`, `1/3`, `corners`, `full screen`, `center`, etc.

As a quick test I quit Rectangle and fired Spectacle back up and I am able to shift between monitors again. Happy to help you debug just let me know what you'd like to know.

**Comment by scottatron** [comment] 2019-09-02 03:00
This may not be limited to displays connected to an eGPU—I recently updated to v0.4 and my Next/Previous Display shortcuts are no longer working. My displays are connected via a Belkin Thunderbolt 3 dock.

I've tried toggling some of the new preferences and assigning new shortcuts, but Rectangle only seems to be aware of the primary display. Have also confirmed my Maximize and Make Smaller shortcuts still work.

**Comment by rxhanson** [comment] 2019-09-02 06:22
Thanks for reporting this! Looks like I broke the next/previous displays in v0.4 with some refactoring. I'm able to reproduce it. 

I'll be pushing out a new release in the next day or so, and a fix for this will go in it. In the meantime, you can grab v0.3 from the [releases page](https://github.com/rxhanson/Rectangle/releases/tag/v0.3).

**Comment by rxhanson** [comment] 2019-09-02 15:06
This should now be fixed in [v0.5](https://github.com/rxhanson/Rectangle/releases/tag/v0.5). Let me know when you get a chance to try it out.

**Comment by caxelair** [comment] 2019-09-03 09:10
Hi,
Indeed it's now corrected. Thanks a lot for the quick fix.

**Closed** 2019-09-03 12:19 UTC

**Comment by stgarf** [comment] 2019-09-03 16:25
Confirming all fixed. Thanks!
