### ISSUE TITLE
Can't set shortcut to "Shift Left/Right/Up/Down"

### ISSUE THREAD

**Issue by jingzhehu** [rxhanson/Rectangle#5] opened 2019-07-22 23:30 UTC
@rxhanson Thanks for making this app available ! 

The problem I have is that I can't set any shortcut to something like "Shift Left" - it just won't be recorded. Could you take a look and help me resolve the issue ?

**Comment by rxhanson** [comment] 2019-07-23 05:16
@jingzhehu thanks for using the app!

The [shortcut recorder](https://github.com/shpakovski/MASShortcut) doesn't allow shortcuts that are already in use by the OS. Shift+arrow is used globally to highlight text. 

At this time, I don't have plans to change this behavior to allow Shift+arrow. It is a really easy change to make in the code, though. If you want to fork it and make the changes, I can walk you through it.

Sorry, probably not the answer you were looking for, but I'm going to close this as "works as intended".

**Closed by rxhanson** 2019-07-23 05:16 UTC
Labels: wontfix

**Comment by jingzhehu** [comment] 2019-07-23 15:03
Got it and thanks in advance ! Could you point me to the relevant source codes ?

**Comment by rxhanson** [comment] 2019-07-23 20:44
I made a quick branch that does what you want. Let me know if you have any questions.
https://github.com/rxhanson/Rectangle/compare/allow-any-shortcut

**Comment by jingzhehu** [comment] 2019-07-24 01:35
@rxhanson Works perfectly ! Really appreciate your help. 

Somehow cocoapod complains about `Unable to find a target named RectangleMAS`. The project builds fine after commenting out the `RectangleMAS` section in `Podfile` and changing some code signing related things.

**Comment by rxhanson** [comment] 2019-07-24 05:35
Thanks for being the first Guinea Pig and letting me know :)
 
I removed the `RectangleMAS` target and reset Xcode to codesign locally in master for the next tinkerers that come along.

If you don't mind, it would help to star the project in GitHub so that it can gain more interest. That will also help me get to 50 stars to add it to brew cask for easy install. Thanks!

**Comment by rxhanson** [comment] 2019-08-29 18:50
@jingzhehu figured I'd let you know that I added the changes for allowing any shortcut into [v0.4](https://github.com/rxhanson/Rectangle/releases/tag/v0.4), so you can get back on the main release track if you want. It's a checkbox in the settings tab of the preferences window.
