### ISSUE TITLE
Semi-transparent Overlay Target missing when Rectangle launches at login

### ISSUE THREAD

**Issue by jmstacey** [rxhanson/Rectangle#176] opened 2020-06-22 04:55 UTC
macOS version: 10.15.5 (19F101)
Rectangle version: 0.30 (35)

Summary: the semi transparent overlay that appears when dragging a window to a screen edge to show where the window will go does not always appear. If the Rectangle app is opened and closed, the the semi-transparent previews appear again for the remainder of the user session.

I suspect the cause is either due to automatic launch on login and/or hide menu bar icon setting.

Reproduce Configuration:
* Launch on Login
* Snap windows by dragging
* Hide menu bar icon

Steps to Reproduce:
1. Configure Rectangle with above settings
2. Reboot Mac and log in
3. Drag window to a screen edge

Expected Behavior: the semi-transparent target should appear

Actual Behavior: the semi-transparent targets do not appear, but the window still snaps as expected (i.e. Rectangle is otherwise still working).

**Comment by rxhanson** [comment] 2020-06-22 18:40
Thanks for reporting. I am unable to reproduce this, so I think this may require some additional logging. I'll post back when I'm able to get a release out for this.

**Comment by jmstacey** [comment] 2020-06-22 19:01
Just noticed on a different device after reboot that the transparent overlay is working after first boot, so this issue might have a different root cause and perhaps be configuration specific. Logging info is blank through Rectangle menu using option click.

**Comment by rxhanson** [comment] 2020-06-27 22:10
Please try out https://github.com/rxhanson/Rectangle/releases/tag/v0.31 and let me know if that makes a difference. I didn't add in logging for v0.31 but will if it doesn't fix it.

**Comment by jmstacey** [comment] 2020-06-29 02:41
Got v0.31 loaded and will keep an eye on it over next few days.

**Comment by jmstacey** [comment] 2020-07-02 04:37
@rxhanson no go with v0.31. On my MBP today after reboot this bug reproduced on the v0.31 pre-release version.

**Comment by rxhanson** [comment] 2020-07-03 11:41
Thanks for posting back. I'll shoot for some logging in next release.

**Comment by dancriel** [comment] 2020-09-04 12:39
I am on macOS 10.13.6 and I think I have this problem too, however it does not seem to matter how the app is launched or if the menu bar icon is hidden, when I try to snap a window to the edge I see a thin white outline but no transparent fill... the outline is really hard to see and I always wondered why the rectangle was not filled in until I found this issue which suggests there should be a fill there... I am using Rectangle v0.32 by the way, I think I started with v0.30 and the rectangle fill never worked, only the thin white outline.

**Comment by rxhanson** [comment] 2020-09-04 13:04
@dancriel This is actually something I'm aware of, as I have an old mac that's stuck on 10.13. I just never got around to fixing it because nobody's mentioned it until now, and it's not possible to load Rectangle in old Xcode versions that don't run Swift 5. I can always do a quick playground or something and see if I can get something that works, but honestly this is pretty low priority compared to other items. If anyone else wants to give it a go, that'd be awesome.

**Comment by dancriel** [comment] 2020-09-04 13:12
That would be very cool for those of us who are sticking with High Sierra. I don't know much about Swift but I am happy to test a beta release if that helps.

**Comment by rxhanson** [comment] 2020-10-19 20:08
In v0.36, I've changed a bit about the "overlay target" window.

@jmstacey If you get a chance, let me know if you still see the issue in v0.36.

@dancriel This should fix the issue on macOS 10.13.

**Comment by dancriel** [comment] 2020-10-19 20:45
Thank you! It works!

**Comment by jmstacey** [comment] 2020-10-21 15:53
@rxhanson was the change already incorporated into hookshot 1.8? I've been using that and it seems to be working well.

**Comment by rxhanson** [comment] 2020-10-21 19:48
@jmstacey This change actually isn't in Hookshot 1.8 - this is one of the few changes I've held off on rolling straight into Hookshot as I've been testing out how Hookshot works with the window fade that I introduced in the latest Rectangle release. 

But, that's pretty encouraging that you haven't been experiencing it with Hookshot. Since nobody else has +1'd this issue and you're not seeing it in Hookshot, I'm going to go ahead and close it out. Feel free to comment or reopen if anything changes on this. The updated window code will go into Hookshot in the next release, and I don't see any reason that it would regress back to showing this type of behavior.

**Closed by rxhanson** 2020-10-21 19:48 UTC
Labels: bug
