### ISSUE TITLE
Window size changes when new tab is opened in Terminal

### ISSUE THREAD

**Issue by rojobuffalo** [rxhanson/Rectangle#705] opened 2022-01-05 17:19 UTC
- [x] This is a new bug that hasn't been documented in a closed issue or in the Readme.

https://user-images.githubusercontent.com/3956993/148259903-5973f8bd-e0ee-4018-8e28-128d235c74b1.mov

When Rectangle has been used on a Terminal window, and then a new tab is opened, the window size changes. The main issue is the width getting smaller. Occasionally the height changes by a couple pixels but imo that's more tolerable than the width changing. If I open Terminal and don't reposition the window with Rectangle, this issue does not happen. In the screencap I positioned the Terminal window as top-half.

The size changes in a slightly different way if I close the second-to-last open tab in Terminal, i.e. if I have 3 tabs, I close one, nothing happens, if I close the second-to-last one so that there's only one tab left, then the window height decreases.

macOS version: 12.1, Mac mini (M1, 2020)
Rectangle version: v0.49 (54)
Logs if applicable (In Rectangle menu, hold option, "View Logging..."): nothing is being logged on these events.

**Comment by rojobuffalo** [comment] 2022-01-05 17:22
Terminal has preferences that control window size, and I have them set to match "top-half" dimensions. When a new tab is opened and the window width gets smaller, it is not matching the Terminal preference width. And if Rectangle is closed or disabled, new tabs can be opened and closed without the window resizing.

**Comment by rojobuffalo** [comment] 2022-01-05 17:33
*this actually happens in macvim as well: new tab makes the window smaller, only when Rectangle has been used to position the window.

**Comment by rxhanson** [comment] 2022-01-06 03:04
Thanks for the detailed report. Although this may be caused by Rectangle having sized the window initially, from my perspective it's not really something that is in Rectangle's scope to fix. As far as I can tell, the undesired size adjustment is not being performed by Rectangle (unless you pull up the Rectangle logging and see otherwise). I'm not sure the setting you are referring to in Terminal, so I haven't tested it out myself, but my guess is that it is something along the lines of Terminal (or macvim) trying to keep the window a specific size based on character widths rather than a free-flowing window size.

**Comment by rxhanson** [comment] 2022-02-15 17:07
Closing this one out since it's not something that I see adjusting Rectangle for. Feel free to comment further if anything new comes up on it.

**Closed by rxhanson** 2022-02-15 17:07 UTC
Labels: bug
