### ISSUE TITLE
Add a "Center Two Thirds" window option

### ISSUE THREAD

**Issue by CaaZaa** [rxhanson/Rectangle#788] opened 2022-04-06 17:35 UTC
Similar to "First Two Thirds" and "Last Two Thirds", a "Center Two Thirds" window option would greatly help my workflow.

**Comment by rxhanson** [comment] 2022-04-11 02:19
Duplicate of https://github.com/rxhanson/Rectangle/issues/52 (and others).

You can use a terminal command to get it: 

https://github.com/rxhanson/Rectangle/blob/master/TerminalCommands.md#almost-maximize

https://github.com/rxhanson/Rectangle/blob/master/TerminalCommands.md#add-an-extra-centering-command-with-custom-size

Alternatively, you can use the custom shortcut builder in [Rectangle Pro](https://rectangleapp.com/pro).

**Closed by rxhanson** 2022-04-11 02:19 UTC
Labels: enhancement

**Comment by PierBover** [comment] 2025-05-14 16:03
I'm missing this feature too.

Is it possible to customize this but for window dragging instead of keyboard commands?

**Comment by rxhanson** [comment] 2025-05-16 06:30
@PierBover Sorry for the delay. At the moment it is not an option in Rectangle. I don't have plans to add it in myself at this time, but see no reason to turn down a pull request for it.

(This is available in Rectangle Pro)

**Comment by PierBover** [comment] 2025-05-16 15:42
> (This is available in Rectangle Pro)

I actually looked at Rectangle Pro and couldn't find this feature.

Are there any docs I could check?

**Comment by rxhanson** [comment] 2025-05-17 05:29
![Image](https://github.com/user-attachments/assets/761eb3fb-29b0-4c3d-a89c-06375a720db7)

![Image](https://github.com/user-attachments/assets/fe89d96f-f5d2-43fa-9895-30175f689959)
