### ISSUE TITLE
Incorrect sizing and positioning with external display since new updates of macOS and Rectangle

### ISSUE THREAD

**Issue by marlonrichert** [rxhanson/Rectangle#94] opened 2020-02-14 07:36 UTC
macOS version: 10.15.3 (19D76) 
Rectangle version: 0.22 (26)

For example…

I try to Maximize by dragging to the top:
![Screen Shot 2020-02-14 at 8 51 58](https://user-images.githubusercontent.com/644725/74508308-6967d800-4f07-11ea-9993-025b3919aa2c.png)
but then this happens:
![Screen Shot 2020-02-14 at 8 52 09](https://user-images.githubusercontent.com/644725/74508324-77b5f400-4f07-11ea-9797-7585b27fb4ee.png)

I try to do Left Half by dragging to the left side of the screen:
![Screen Shot 2020-02-14 at 9 31 21](https://user-images.githubusercontent.com/644725/74510606-cf0a9300-4f0c-11ea-88bf-3305dbdcd2b1.png)
but then this happens:
![Screen Shot 2020-02-14 at 9 31 28](https://user-images.githubusercontent.com/644725/74510633-dd58af00-4f0c-11ea-876e-fef3687edf3e.png)

Similar (but different!) unpredictable things happen when using the keyboard shortcuts or the menu, and it seems to vary from app to app.

Restarting Rectangle doesn't help, but **restarting the app does.** 😮❓

Unplugging my external display also seems to fix the problem —until I plug it back in.

**Comment by marlonrichert** [comment] 2020-02-14 07:37
Also, when an app is affected by this behavior, it resizes really slowly.

Apps that behave correctly resize instantly.

**Comment by rxhanson** [comment] 2020-02-14 08:56
This appears to be an odd manifestation of this issue: https://github.com/rxhanson/Rectangle/issues/29, which I haven't solved and had chalked it up as something that most likely will have to be fixed Apple side.

Did you recently install any other apps that required you to check the box in System Prefs -> Security & Privacy -> Privacy -> Accessibility? 

The main thing that appears to be different for your issue is that the external monitor affects it.

What's the make/model of your external monitor? I'll pass this to Apple when I create a bug report for them.

**Comment by marlonrichert** [comment] 2020-02-17 09:15
I have an Asus PB278.

**Comment by sic2** [comment] 2020-02-24 09:44
Same issue here. Interestingly, I experienced this first with spectacle and then switched to rectangle in the hope that it was fixed but....no no

**Comment by rxhanson** [comment] 2020-02-24 09:48
@sic2 That's because it's a macOS bug. It is actually a big help if anyone that has this issue can file a bug with Apple - the more people that file it, the more likely it will be fixed.

**Comment by sic2** [comment] 2020-02-24 12:57
@rxhanson what details are you submitting for the apple bug? 
It is unclear what info should be added in their bug report.

**Comment by rxhanson** [comment] 2020-02-24 13:13
@sic2 I haven't actually submitted mine yet because I have not reproduced it on my mac running Catalina. I can reproduce it on my older mac, but I'd rather send the macOS sysdiagnose and System Information Report from an up-to-date system. My draft issue description looks like this:

> I'm the developer of an open source window management application called Rectangle (https://github.com/rxhanson/Rectangle). Rectangle uses the accessibility API to move and resize windows. 
> 
> When certain other apps are running that also require accessibility privileges, some apps do not move and resize properly. I was able to reproduce it consistently with an app called Punto running, and it has also been noted with Dragon running. This behavior has also been noted when an external monitor is attached (Asus PB278), without other accessibility applications enabled.
> 
> Steps to reproduce:
> 1. Install Rectangle (https://rectangleapp.com)
> 2. Install Dragon (https://www.nuance.com/dragon.html) or Punto (https://yandex.ru/soft/punto/)
> 3. Attempt to resize Google Chrome using Rectangle (cmd + alt + right arrow, etc).
> 
> When an app does not properly move/resize, the moving and resizing that it does exhibit has an animation to it, and it is not instantaneous. The typical, correct behavior is instantaneous and does not animate.
> 
> This is currently an issue on macOS 10.15.3, and has been noted on previous versions of Catalina and previous versions of macOS.
> Here are two GitHub issues that have been filed for it:
> https://github.com/rxhanson/Rectangle/issues/29
> https://github.com/rxhanson/Rectangle/issues/94
> 
> In the first one, there's a gif that shows what the incorrect move/resize behavior looks like. 
> 
> This behavior is external to the Rectangle app. I am unaware of anything that could be done from a 3rd party perspective to correct this behavior. I've also noted similar behavior with other apps of this kind, like Magnet. 

Of course, your description will probably look a little different since you might have other steps for reproducing it.

Thanks! I'll report back when I get mine submitted and if I hear anything back.

**Comment by mpetersen** [comment] 2020-02-27 13:53
I revoked accessibility permissions for some applications that I don't use anymore, which resolved that issue for me.

System Preferences > Security & Privacy > Privacy > Accessibility

**Comment by rxhanson** [comment] 2020-03-25 21:03
Just a quick update on this one. I did submit my bug to Apple but I am going with the assumption that it will take a really long time before this gets fixed Apple side, if at all.

So, I have looked at what it would take to get a Rectangle workaround up. 

Basically, the issue is that under certain circumstances, window resize animation is enabled for certain apps. In the case of this issue, it's the external monitor being plugged in. I was able to reproduce it consistently by having the macOS on-screen keyboard displayed. Despite the accessibility API actually properly receiving the window move/resize commands, the animated resize will stop wherever it is when it receives another move/resize command. In order for Rectangle to workaround this bug, there would need to be delays built into each move/resize command sent to the accessibility API. That means that when animated resize is enabled, window move/resize by Rectangle would be, well, slow. There's kind of a way to automatically detect this happening, but it would add a decent amount of complexity to the code - so the simplest way to enable the delay would be via a setting. It's also a bit painful to add the delay because it requires currently synchronous code to be updated to become asynchronous. The absolute best scenario here is that Apple does fix it at some point :(

It'll take me a while to get back to update Rectangle with a workaround, but I'll post back here when I do.

**Comment by marlonrichert** [comment] 2020-04-04 15:15
So, if I didn't have window resize animations enabled, this wouldn't be a problem for me anymore? How do I turn them off? I don't need them.

**Comment by rxhanson** [comment] 2020-04-04 18:06
@marlonrichert For me, the resize animations still occur even when macOS animations have been turned off. There might be some more settings in macOS to try?

**Comment by M4DMojO** [comment] 2020-04-07 19:21
Hello.
From the first release of Catalina up to the current 10.15.4, I have the same issue, and it happens on my MacBookPro 16 screen  or my side displays (IIYAMA or my LG 5K). When I reboot I usually have a normal behaviour but quickly the windows do not behave as expected. I have setup a screencast, with a virtual keyboard showing what I am doing with the keys and displayed the log. May be this can help. Also, Terminal sometimes works fine while other windows (firefox, finder) are not responding correctly. Here is the link to the video : https://www.dropbox.com/s/oho68mssa9bks1b/Enregistrement%20de%20l%E2%80%99%C3%A9cran%202020-03-10%20%C3%A0%2010.56.34.mov?dl=0

Cheers.

**Comment by JakeElder** [comment] 2020-04-12 09:07
Such an annoying issue! Does anyone know of a window manager that isn't affected by this or has developed a workaround?

Thank you to @rxhanson for looking in to the cause of the change in behaviour and filing a bug with Apple 🙏. (And building this to begin with 👊)

**Comment by rxhanson** [comment] 2020-04-12 10:23
Let me reiterate: 

> It is actually a big help if anyone that has this issue can file a bug with Apple - the more people that file it, the more likely it will be fixed.

> The absolute best scenario here is that Apple does fix it at some point

What you want is for Apple to fix the bug. Even if Rectangle or another app creates a workaround, it's just that... a workaround. Please file the bug with Apple if you experience it... that's better than asking for alternative apps in issues for Rectangle.

**Comment by JakeElder** [comment] 2020-04-12 10:54
Hi @rxhanson - I read your comment thoroughly, and understand what you're saying.

> What you want is for Apple to fix the bug.

What I want is to be able to manage my windows, as I expect do other users of your software. Would you expect me to use this software while it isn't working as expected, instead of using another piece of software that does work as expected?

Is your bug report public, or something that can be upvoted? If not can I ask where (at what url) you reported the issue and how you described it? I'm not sure I have an enough of an understanding of the issue to articulate it in a bug report.

Thanks

**Comment by rxhanson** [comment] 2020-04-12 11:11
If you are a developer, file an issue here:
https://feedbackassistant.apple.com/

If you are not a developer, use:
https://www.apple.com/feedback/macos.html

> I'm not sure I have an enough of an understanding of the issue to articulate it in a bug report.

Just describe what happens and if there are steps to reproduce it. I think support at Apple should be able to figure out that this issue is the same as what other people are reporting.

> What I want is to be able to manage my windows, as I expect do other users of your software. Would you expect me to use this software while it isn't working as expected, instead of using another piece of software that does work as expected?

I'm not trying to be rude, just matter of fact. Asking for alternatives is not assistive to solving this issue, unless it is with the intent to say, here is a good way that it's solved - let's see if we can replicate it.

**Comment by M4DMojO** [comment] 2020-04-12 15:18
Hello.

I did not get enough time to file a report to Apple, I was planning to do it as per tuesday.

I have updated with the last 10.15.4 bundle => 19E287 (I was already in 10.15.4 before but I did not write the build number) which was available friday the 10th for me and everything seems to be working fine since the update. This is now 2 days I do not have the issue anymore.

Same for you too guys ?

So far I have recovered the smooth transition and the windows are correctly resizing as I command. I am still running Rectangle 0.24(28).

Hopefully Apple fixed the issue.

**Comment by rxhanson** [comment] 2020-04-12 17:46
@M4DMojO I can still reproduce it with the same build of macOS using the on-screen keyboard, the only way that I could consistently reproduce it before. Was your issue the same as @marlonrichert - connecting a monitor?

**Comment by mB-PiBox** [comment] 2020-04-12 19:39
Not sure if this is helpful, but Im having the same issue displayed in the original issue post where dragging to the screen edge, results in the window being placed oddly.

I only have 1 monitor; buts its a 34" LG 5K Ultrawide. And I don't have any other apps enabled in the Security & Privacy>Accessibility permissions, just Rectangle.

I'm able to Quit the Rectangle app, then relaunch to get everything back to working as it should. But it eventually goes back to acting weird, requiring another restart of the app. 

I'm on the most recent release of macOS Catalina 10.15.4 - which it just updated a couple days ago to fix some FaceTime bugs and such.. but the issue started a few months ago.

**Comment by M4DMojO** [comment] 2020-04-12 23:51
> @M4DMojO I can still reproduce it with the same build of macOS using the on-screen keyboard, the only way that I could consistently reproduce it before. Was your issue the same as @marlonrichert - connecting a monitor?

It's hard to tell what was triggering the weird positioning behaviour. I experienced the problem after few hours after a reboot. Usually just after a reboot every app (firefox, mail, terminal, adobe, office...) would behave normally, then it would go berserk like my video or the case shown in issue 29 [Here](https://github.com/rxhanson/Rectangle/issues/29). Since I nearly always have a second screen on (IIYAMA (HDMI) at work, LG 5K (ThunderBolt/USBC like connector) at home), the problem was occuring at each places and whatever the screen (MacBook Pro 16 or External screen). Not only the window would not resize at the correct place but sometimes trying to shove the window on the right would keep on moving them on the left. Sometimes Mail would not work while terminal was still OK (ie: slow resizing and bad positioning on mail, while terminal would position correctly and fast).
Now since the last update (10th of April) of Catalina, it's all perfect and I did not change my Rectangle version. This would hopefully mean that Apple has fixed something in this release.

**Comment by mB-PiBox** [comment] 2020-04-13 00:44
> > @M4DMojO 
> Now since the last update (10th of April) of Catalina, it's all perfect and I did not change my Rectangle version. This would hopefully mean that Apple has fixed something in this release.

That seems possible, but I have the most recent release of Catalina, and I'm experiencing the issue. Rectangle will work find after a restart (of either the Mac or the app itself) but eventually will go back to snapping windows half off-screen, or in odd places when dragging to the top to maximize. Even the keyboard shortcuts snap the window in the same odd position, and not where they should be. 

I notice it starts to have issues after I've woken it from sleep a few times, but not always. It will start having issues also after a few hours of continues use, but waking it from sleep a few times within a couple hours also increase the speed at which the issue starts happening (if that makes sense)

Did you change anything, settings, permissions, etc, beside just installing the update? So I might make the same changes to see if it resolved the issue for me as well..

**Comment by M4DMojO** [comment] 2020-04-13 09:45
Hello,
I used to experienced exactly the same issue with time span I could not exactly analyse, but your descriptions definitely ring a bell to me and match my experience. I have not changed any settings, just updated Catalina with the last patch (19E287). note that it was already 10.15.4 before this patch. I am on a MacBook Pro 16, don't know if the patch is generic and for all machines. I will try to sleep and wake the computer to see if it comes back. But so far that is the 3rd day with a normal behaviour. Which is way longer than the usual half day before it goes berserk.

**Comment by M4DMojO** [comment] 2020-04-13 13:14
I am having second thoughts, I went back in the accessibility settings and I remember that I have may have removed the : Settings > Accessibility > Zoom > unchecked the Enable Hover Text and also Use Keyboard shortcuts to zoom.

**Comment by mB-PiBox** [comment] 2020-04-13 13:55
> I am having second thoughts, I went back in the accessibility settings and I remember that I have may have removed the : Settings > Accessibility > Zoom > unchecked the Enable Hover Text and also Use Keyboard shortcuts to zoom.

Unfortunately I never had that Accessibility option enabled, so can not disable to see if it resolves issue.

>updated Catalina with the last patch (19E287). note that it was already 10.15.4 before this patch. I am on a MacBook Pro 16, don't know if the patch is generic and for all machines

It was a universal patch, due to issue with FaceTime calls.. believe also went out to iOS devices. I have that update as well, but still having issue with Rectangle :(

**Comment by rxhanson** [comment] 2020-04-13 18:56
I've built a rough workaround alpha build for this issue, if anyone is willing to try it out:
https://github.com/rxhanson/Rectangle/releases/tag/v0.25.1

**You have to configure it with a terminal command, though**

This release adds in logic for how long to wait between each window move/resize command for the window to finish animation. Since it varies, and I have no idea how long it could take for you, I'm forcing you to configure it with this command:

`defaults write com.knollsoft.Rectangle animationDelay -int 300`

`300` is my arbitrary number of milliseconds to wait between every size and position call made to each window, and can be adjusted as seen fit. It's a number that worked OK for me - still had issues with some resizing, but each command means potentially 2-4 delays (up to 1.2s for a window resize. ugh!)

Note that there are existing issues here - repeated shortcut execution does not perform 2/3 and 1/3 sizes (if configured), and 300 ms might be on the low end of what is needed to allow the window to fully resize from/to certain sizes/positions.

At this time, I have no plans to pursue this path farther, but feel free to take the animation-delay branch and tweak it. As such, I'm closing this issue and leaving with the recommendation to file a bug with Apple.

**Closed by rxhanson** 2020-04-13 18:56 UTC

**Comment by stevenqzhang** [comment] 2020-06-12 05:30
> I've built a rough workaround alpha build for this issue, if anyone is willing to try it out:
https://github.com/rxhanson/Rectangle/releases/tag/v0.25.1

This worked for me! running three monitors on 10.14.6

**Comment by rxhanson** [comment] 2020-06-12 07:59
@stevenqzhang Sorry, no plans to merge this with the main branch. In order to add those delays, the window move/resize logic had to be changed to be asynchronous instead of synchronous for v0.25.1, which introduces some breaking changes for some of the app behavior like repeated shortcut executions. This issue affects a relatively small percentage of users from what I can tell, and the better user experience by far is the snappy synchronous behavior from my perspective. Perhaps with enough users filing issues to Apple, the bug will be fixed macOS side.

**Comment by stevenqzhang** [comment] 2020-06-12 22:53
Got it, thanks for the update and taking the time to do this fix!

**Comment by rxhanson** [comment] 2020-12-11 11:05
This should now be fixed in [v0.40](https://github.com/rxhanson/Rectangle/releases/tag/v0.40).
