### ISSUE TITLE
windows not being restore to their initial size after unsnapping

### ISSUE THREAD

**Issue by lethargosapatheia** [rxhanson/Rectangle#603] opened 2021-10-14 20:49 UTC
- [x] This is a new bug that hasn't been documented in a closed issue or in the Readme.

macOS version: big sur 11.6
Rectangle version: 0.48
Logs if applicable (In Rectangle menu, hold option, "View Logging..."): --

The problem that I'm having with rectangle is that the windows are not restored to their initial size after they're unsnapped if I move "too fast", as it were. "Too fast" meaning natural in my case. If I keep my finger on my trackpad a little longer (maybe 1 second), then the window regains its initial size. If I don't, the whole window is moved and it keeps the shape and size that it had while being snapped to some random edge.

**Comment by lethargosapatheia** [comment] 2021-12-16 21:16
Hello,

I know you most probably have a lot on your plate, but I wanted to ask if there were any plans to solve this issue. It really affects the experience.

Regarding the logs, it seems that there is an actual error. So, as I said, normally if I do it slowly (that is to say, if I de-snap it), the window is restored to its initial size and these are logs:
```
2021-12-16T23:13:59+02:00: AX sizing proposed: (962.0, 722.0), result: (962.0, 722.0)
2021-12-16T23:14:03+02:00: AX sizing proposed: (840.0, 964.0), result: (840.0, 964.0)
2021-12-16T23:14:03+02:00: AX position proposed: (840.0, 25.0), result: (840.0, 25.0)
2021-12-16T23:14:03+02:00: AX sizing proposed: (840.0, 964.0), result: (840.0, 964.0)
2021-12-16T23:14:03+02:00: rightHalf | display: (0.0, 61.0, 1680.0, 964.0), calculatedRect: (840.0, 25.0, 840.0, 964.0), resultRect: (840.0, 25.0, 840.0, 964.0), srcScreen: Built-in Retina Display, destScreen: Built-in Retina Display, resultScreen: Built-in Retina Display
```
Now, when I do it fast:
```
2021-12-16T23:14:05+02:00: Unable to obtain window id
2021-12-16T23:14:05+02:00: Unable to obtain window id
2021-12-16T23:14:05+02:00: Unable to obtain window id
```

**Comment by rxhanson** [comment] 2021-12-16 23:03
Thanks for checking back in on this one. 

I can't really reproduce it on my end, hence it not being prioritized, but I'll take another look.

**Comment by lethargosapatheia** [comment] 2021-12-16 23:15
It's probably also relevant to mention that I tested this initially on catalina (mbp 15) and now I'm testing it on monterey (mbp m1) and the behaviour is identical.

**Comment by lethargosapatheia** [comment] 2021-12-18 19:04
I'm adding a video to demonstrate visually the issue that I'm having:
https://user-images.githubusercontent.com/22618815/146652928-cbe6f57b-b722-47b7-ab7b-44694b193252.mov

.

**Comment by rxhanson** [comment] 2022-01-14 03:00
Just a heads up that I am finally digging into this one. I have been able to reproduce it really sporadically. It might require a couple of tries to get it right since it's some delicate timing though. I'll post here when there's a beta build ready.

**Comment by rxhanson** [comment] 2022-01-18 03:00
When you get a chance, can you test out this beta and let me know what you find?

https://github.com/rxhanson/Rectangle/releases/tag/v0.50.1

**Comment by lethargosapatheia** [comment] 2022-01-18 13:11
Hello. Thanks for the work. Unfortunately I'm experiencing the exact same behaviour. And it's very consistent as long as I drag the window fast enough from its snapped position.

The test that I'm doing now is with Firefox and I'm snapping it to the right (so it takes up half of the screen). Then when I drag the window to the left, it keeps its size and shape instead of returning to its original size.

I think this is also **important** to note: I release (remove my finger from) the trackpad almost immediately after I drag the window to the left.
If, on the other hand, I keep my finger pressed while moving it, it seems to work correctly in a consistent way.

It's just that I don't use it that way, I remove my finger immediately. This is how I've found out, for me it's natural :)

I've tested it on macbook pro m1 Monterey and Macbook Pro 2015 Monterey (previously I had Catalina installed, with the same behaviour).

**Comment by rxhanson** [comment] 2022-01-19 02:42
I see. Thanks for testing this out so quickly and for the additional info.

This might boil down to an inability to rapidly catch the right information as a third party on mouse drag.

As a workaround, does it make sense to build a check on mouse up since you remove the mouse so quickly? This would likely be more robust than what is currently done on drag event since drag events can flood the event stream and that's likely what's preventing Rectangle from quickly knowing that it should unsnap restore.

**Comment by lethargosapatheia** [comment] 2022-01-21 01:40
I really cannot judge that really, I don't have programming experience and in any case not in this field, but I'm trying to understanding. How do you mean "a check on mouse up"? "Mouse up" un-clicking basically?

**Comment by rxhanson** [comment] 2022-01-21 01:45
Yes to un-clicking. In other words, would it be strange to you if the restore happened when you un-clicked, as it doesn't happen for you immediately upon dragging the window?

**Comment by lethargosapatheia** [comment] 2022-01-21 01:54
Well, it might feel slightly strange, I guess, but I would suspect it would bother me to a substantially lesser extent in any case, because I would eventually get what I wanted and could manage the windows properly, as the information of the window size wouldn't be lost anymore. So the trade-off seems reasonable at first sight.

I'm not sure if other users would like that in particular, as the change could be rather important. But this isn't for me to say.

**Comment by leebickmtu** [comment] 2022-02-09 17:39
Just wanted to add since no other user had confirmed this bug that I am able to reproduce with consistency.

Following @lethargosapatheia step of right half snapping window and then quickly unsnapping vs slowly unsnapping.
Able to reproduce with both Firefox and Finder windows.

Mac OS: 10.5.7
Rectangle: 0.50

**Comment by leebickmtu** [comment] 2022-02-09 17:51
My guess is the time between the mouse down and mouse up is so small with the fast unsnap flick that Mac OS just doesn't even issue a drag event. Might be too small of a time window to trigger their drag polling.

My suggestion would be a hybrid approach to what is currently done and what you suggested Ryan.

If on mouse up event, Rectangle can see the window position moved from being snapped then restore the window geometry.
But if a drag event was received prior to mouse up then restore geometry immediately without waiting for the mouse up.

That way when slow dragging the user doesn't have to wait for mouse up release to see the size change.

**Comment by rxhanson** [comment] 2022-02-18 17:15
I added in the unsnap on mouse up in v0.51. 

https://github.com/rxhanson/Rectangle/releases/tag/v0.51

**Comment by leebickmtu** [comment] 2022-02-18 18:23
Just updated to 0.51 and tested. Can still reproduce the issue, doesn't seem to have helped.

**Comment by lethargosapatheia** [comment] 2022-02-18 18:25
Same here. Can't see any difference.

**Comment by rxhanson** [comment] 2022-02-28 16:07
Please try v0.53 and let me know if that changes anything:
https://github.com/rxhanson/Rectangle/releases/tag/v0.53

**Comment by lethargosapatheia** [comment] 2022-03-13 13:12
Unfortunately I'm still not seeing any difference. I'm not sure exactly how I could help better with testing, but let me know if I can do something in that respect.

**Comment by rxhanson** [comment] 2022-03-13 13:37
Thanks for continuously trying out the updates and posting back. 

From my perspective, I have maxed out what can be done from Rectangle's side for this issue. In my testing, it does perform the restore when quickly unsnapping. But there's always other factors that can affect other users, especially in an app that operates at this level, and we could be at a point where it's just a macOS limitation.

I'm going to close this issue, but anyone is welcome to dig into things further and see what they can do.

**Closed by rxhanson** 2022-03-13 13:37 UTC
Labels: bug

**Comment by lethargosapatheia** [comment] 2022-12-15 19:53
I'm not sure what you did in your last update, but you seem to have fixed it. At least this is my impression in the last 5 minutes - the bug isn't there anymore and the windows are getting restore to their original size. It'a also possible that I haven't explicitly tested this since upgrading to Ventura, but I can't be 100% sure. Maybe @leebickmtu has something to say about that.

**Comment by leebickmtu** [comment] 2022-12-15 20:02
I am still able to reproduce on v0.64, however I'm also still on Catalina 10.15.7.

So maybe the Ventura OS update plays a role, I'll you know if/when my business finally unblocks OS updates past Catalina.

**Comment by leebickmtu** [comment] 2023-06-21 18:04
Finally got upgraded to Ventura 13.3.1 from Catalina.
Can confirm the bug no longer exists, so does appear to have been something in the OS got fixed.
