### ISSUE TITLE
Rectangle doesn't start at login/startup

### ISSUE THREAD

**Issue by razorree** [rxhanson/Rectangle#561] opened 2021-09-01 09:00 UTC
System Version:	macOS 11.5.2 (20G95)
Kernel Version:	Darwin 20.6.0
(updated today),

but before it didn't start as well (i've installed Rectangle about 1-1.5 month ago, never started automatically)

Version 0.48 (53), icon visible (so i can see when it's running)

**Comment by rxhanson** [comment] 2021-09-01 23:57
If you toggle the setting for launch on login off, then on, does it work then?

**Comment by rxhanson** [comment] 2022-01-06 03:20
Rectangle uses an embedded helper app to launch itself on login. We can tell if the helper gets registered with macOS using this: https://github.com/keith/SMLoginItems. Let me know if it's there. If it isn't then at least we know there's a problem with getting it registered. If it is, then we know that there's a problem with the helper actually launching. This seems to affect a really small number of users. Is there anything on your system that could prevent an app from registering itself with macOS?

One more thing that might fix it is if you delete Rectangle (cmd+option+delete in finder), then install it from a fresh download. This would clear out the registered (cached) helper app from macOS.

**Comment by snevs** [comment] 2022-12-19 13:21
Same behavior as @razorree described with all the details. I checked the SMLoginItems, and Rectangle is not there.

**Comment by rxhanson** [comment] 2023-03-22 13:13
@lgarron Thanks for reporting. I track Rectangle Pro issues in a separate repository, and I made an issue for this there: https://github.com/rxhanson/RectanglePro-Community/issues/244

Closing this one out since Rectangle has also been migrated away from the SMLoginItems way of doing it in Ventura, and if there are further issues, it would be best to have this as a new issue with updated information.

**Closed by rxhanson** 2023-03-22 13:13 UTC
Labels: bug

**Comment by chrismillerkeys** [comment] 2023-09-25 18:26
I have this issue as well. Rectangle was installed via Homebrew on Ventura 13.6 (M2 Max Mac Studio), and it doesn't matter whether I drag-n-drop the app into Login items, click the app's checkbox to Launch at Startup (also unchecked and rechecked), or click the [+] button in Startup Items. When installed via Homebrew, the app does not register as a startup item, as confirmed by the SMLoginItems tool. This was working fine right before the 0.72 update.
p.s. I love this app, thanks so much for your hard work on it!!

**Comment by rxhanson** [comment] 2023-09-25 19:48
@chrismillerkeys I'll keep the tracking on this in https://github.com/rxhanson/Rectangle/issues/1238#issuecomment-1734269159 going forward.
