### ISSUE TITLE
Center command ignores dock

### ISSUE THREAD

**Issue by AlexandruIstrate** [rxhanson/Rectangle#489] opened 2021-06-11 16:01 UTC
When I use the center shortcut, Rectangle ignores the dock and calculates the center of the screen as if the dock wasn't there.

macOS version: 11.4 (20F71)
Rectangle version: 0.47 (52)
Logs if applicable (In Rectangle menu, hold option, "View Logging..."): No logs

Behaviour:
https://user-images.githubusercontent.com/38143225/121715185-7cc48c80-cad6-11eb-8508-74a7dd221b0d.mov

**Comment by rxhanson** [comment] 2021-06-11 18:38
In short, this is an issue with macOS. Rectangle does not calculate dock size for any of its calculations, it just asks macOS for the usable screen size, and that size is supposed to take into account the size of the dock. In a few scenarios, macOS fails to tell Rectangle the proper usable size of the screen, minus the dock. I am not aware of any public macOS api's that will provide the dock size, so it's basically out of the control of Rectangle. This is noticed in a few other issues, but it ultimately boils down to the same root cause.

**Comment by AlexandruIstrate** [comment] 2021-06-13 16:54
Yeah, I guess that if it's an OS issue you can't really fix it. Though, I've noticed that a restart or a sleep seems to fix it.

**Comment by rxhanson** [comment] 2021-06-13 18:34
This root issue was reported many years ago with Spectacle as well (among other window managers). Typically, this resolves itself after executing another window management command or hiding/showing the dock, but it sounds like that might not be the case for you?

There are some workarounds for it, but none that I would be inclined to add in. 

Since this isn't something I have plans to make changes in Rectangle for, I'm going to close this one out. Feel free to comment if anything about this issue changes. If anyone wants to dig into the code, let me know and I can give some entry points.

**Closed by rxhanson** 2021-06-13 18:34 UTC
Labels: bug

**Comment by rxhanson** [comment] 2024-02-05 16:31
It's been a long time since I've looked into this, so maybe there's something I've missed. If anyone wants to give it a go, I see no reason to turn down a good pull request here.
