### ISSUE TITLE
Cannot use Rectangle in Microsoft Excel

### ISSUE THREAD

**Issue by CzarScar** [rxhanson/Rectangle#766] opened 2022-02-25 01:28 UTC
macOS version: macOS Monterey 12.2.1
Rectangle version: 0.51(57)

All the menu become grey when in Microsoft Excel App

**Comment by rxhanson** [comment] 2022-02-25 03:03
Can you attach what happens in the logs when you open the menu?

In the menu bar menu, hold option and select view logging. Then reproduce the issue.

**Comment by CzarScar** [comment] 2022-02-25 07:25
Thank you for your quick response.

When I use the Rectangle in Excel, the log just shows like below:

2022-02-25T15:23:40+08:00: Unable to obtain accessibility element
2022-02-25T15:23:41+08:00: Unable to obtain accessibility element
2022-02-25T15:23:41+08:00: Unable to obtain accessibility element
2022-02-25T15:23:41+08:00: Unable to obtain accessibility element
2022-02-25T15:23:42+08:00: Unable to obtain accessibility element
2022-02-25T15:23:42+08:00: Unable to obtain accessibility element
2022-02-25T15:23:42+08:00: Unable to obtain accessibility element
2022-02-25T15:23:42+08:00: Unable to obtain accessibility element
2022-02-25T15:23:42+08:00: Unable to obtain accessibility element
2022-02-25T15:23:43+08:00: Unable to obtain accessibility element
2022-02-25T15:23:43+08:00: Unable to obtain accessibility element
2022-02-25T15:23:43+08:00: Unable to obtain accessibility element
2022-02-25T15:23:48+08:00: Unable to obtain accessibility element
2022-02-25T15:23:49+08:00: Unable to obtain accessibility element
2022-02-25T15:24:49+08:00: Unable to obtain accessibility element

Hope this could provide you the help.

**Comment by ftorelli165** [comment] 2022-02-28 17:10
I have the same issue running v0.53. I also have BetterTouchTool and it has not been working with Excel either since upgrading to Monterey.

**Comment by rxhanson** [comment] 2022-02-28 17:22
Thanks for following up. Unfortunately this points to an issue on Excel's side, where it's not working with the macOS Accessibility API that is used by Rectangle to modify window position/size. Sometimes restarting the app you're trying to resize will work, but I'm guessing you already have done that. Closing this one out, since there are no more changes that make sense to try on Rectangle's side.

**Closed by rxhanson** 2022-02-28 17:22 UTC
Labels: bug

**Comment by CzarScar** [comment] 2022-03-01 08:16
Hi @rxhanson Thank you for you info. I have upgraded to the latest version. And it works after restarting Excel. Great job. Thank you again. And thank you for providing such a good resize tool.
