### ISSUE TITLE
less shortcut keys with cycle through

### ISSUE THREAD

**Issue by hfcheng66** [rxhanson/Rectangle#156] opened 2020-05-20 21:55 UTC
Sorry this is not really a bug for Rectangle, but it says it is not accepting new features. It was initially posted on Spectacle repo and rxhanson asked me to post it here for tracking purpose. Below is the my original post at Spectacle repo. Please let me know if anyone knows any other shortcut software on MAC that have those cycle through keyboard shortcuts feature, thanks!

=======================
I am looking for the move and resize keyboard shortcuts on Mac and find Spectacle and Rectangle.

I'm on macOS 10.14.4, Spectacle 1.2. The "next third" does cycle through all 6 positions both horizontally and vertically. I use this ALL the time and use the cycle way to move windows to desired position. In fact I disabled "previous third" shortcut. It is one less shortcut to remember and use cycle way is pretty fast.

It is not that easy to remember so many shortcut keys. I'm hoping there are another cycle shortcut key available to other type of move/resize. For example take Rectangle's shortcut key:

- left half, right half, top half, bottom half can use one shortcut key to cycle them.
- top left, top right, bottom left, bottom right can use one shortcut key to cycle them.
- first third, first two thirds, center third, last two thirds, last thirds (vertical+horizontal, 10 positions) can use one shortcut key to cycle them.
- maximize, restore can use one shortcut key to cycle them.
- next display, can cycle through all displays
- ....

With big/wide monitor, we can even have 1/6 cycle through all 6 positions.

This ways the number of shortcut keys are dramatically reduced, not only make it easy to remember not also reduce the chance of conflicting with other application shortcut keys.

What do you think? Is this possible?

Thanks!

**Comment by rxhanson** [comment] 2020-05-20 22:36
Thanks for posting it here. I prefer to have a conversation about potential Rectangle functionality here, despite the current restriction on additional features :)

In the case of the identical Spectacle functionality, I think I would personally rather memorize yet another keyboard shortcut than press the same one 6 times to get a window where I want it, but that's just me. 

I can see the benefit of this for certain actions, though. I've given this type of thing a lot of thought for my paid app, [Hookshot](https://hookshot.app). I drew up a UI for customizing repeated actions that I plan on adding into Hookshot, but it'll be a while before I get around to it. I rarely use a keyboard shortcut now after I created Hookshot, though.

I'll leave this issue open in case anyone wants to implement any of these with a Terminal command flag for them.

**Comment by cmcginty** [comment] 2020-07-08 22:50
Just upgraded to rectangle and I also am missing this key behavior. I really like the cycle modes in spectacle for 1/3 view. In rectangle, its really awkward because the cycle direction is reversed. For example if you snap to the "right 1/3" then go right again, the pane moves to the next left position. Spectacle had these reversed so cycling right would always move the pane right.

For me, it doesn't make sense why you would want to change this behavior.

**Comment by rxhanson** [comment] 2020-07-09 18:15
I'm not opposed to the Spectacle behavior and have no reasons to turn down a PR for that functionality.

**Comment by villaineyed** [comment] 2020-09-07 04:07
If I could comment here too. I think I'm on topic.

I would love the option to map the a key-combo to different positions, where repeated entries flips between them. Similar (but not identical) to hfcheng66 and cmcninty above, I would love to have one key-combo that switches between left half and right half, and another that switches between left third, middle third, right third, etc. but I want to be able to choose which window positions are linked to a key-combo.

If this is possible in Hookshot, I'd be happy to pay for that, but it appears that Hookshot uses mousing/trackpad, which isn't my preferred method of windowing interaction.

Thanks!!

**Comment by rxhanson** [comment] 2020-09-07 19:55
@villaineyed This is actually something I'm working on for the next release of Hookshot. I was working on it for Rectangle but it didn't feel like it fit there as it's a bit more complex of a UI than makes sense to add into Rectangle (I strongly prefer keeping Rectangle as simple as I can). I'll post back when I have an initial release of this functionality in Hookshot, if you're still interested.

**Comment by villaineyed** [comment] 2020-09-10 06:26
Sounds great! Thanks.

I haven't looked at Hookshot yet, but please also consider (if it's not in there yet) allowing for arbitrary window sizes (either as percentages or user-defined grids) so that, e.g., I could have horizontal ¼-screen (or 1/5 or 1/6) windows, or a 57% window on the right side. Thanks!

**Comment by drorata** [comment] 2020-09-11 13:05
It seems like this option is now available in version v0.32:

<img width="500" alt="Screenshot 2020-09-11 at 15 03 54" src="https://user-images.githubusercontent.com/2905978/92928937-14118c00-f440-11ea-9cb8-e3eb77e48827.png">

However, I think there's a bug - the cycling is active when **not** checked. Can anyone confirm? Or am I completely off topic here :)

**Comment by drorata** [comment] 2020-09-11 15:28
Thanks for the clarification and sorry for the noise. Can you maybe confirm that indeed there's a bug in the toggling?

**Comment by rxhanson** [comment] 2020-09-11 16:30
@drorata I think the wording of the preference there might be what's throwing you off. Having that "Cycle across displays..." setting unchecked means that Rectangle will operate like Spectacle, where repeating the shortcut will perform 2/3 then 1/3 window sizes.

You can disable the "repeated executions" behavior altogether with the Terminal command here: https://github.com/rxhanson/Rectangle#halves-to-thirds-repeated-execution-of-half-and-quarter-actions

Let me know if that still doesn't make sense.

**Comment by drorata** [comment] 2020-09-11 18:19
@rxhanson I'm afraid it is still confusing for me. If checked, it means that cycling across the displays is in place. Spectacle is not mentioned in this context I think.

**Comment by rxhanson** [comment] 2020-09-11 18:30
@drorata If you have the checkbox checked, here's the expected behavior for right half keyboard shortcut:
1st execution - Move frontmost window to the right half of the current display (monitor).
2nd execution - Move this window to the left half of the next display/monitor.

If you don't have the checkbox checked, then you should have this behavior for the right half shortcut:
1st execution - Move frontmost window to the right half of the current display (monitor).
2nd execution - Make this window take up the right 2/3 of the current display.
3rd execution - Make this window take up the right 1/3 of the current display.

If you want neither of those behaviors, then you can execute that mentioned Terminal command.

**Comment by rxhanson** [comment] 2020-09-13 06:55
@villaineyed I've added my first cut of user defined shortcuts with repetitions to Hookshot v1.7. I think it should cover what you're looking for. Here's a screenshot with an example that just does left and right half with the same shortcut.

![Screen Shot 2020-09-13 at 8 48 37 AM](https://user-images.githubusercontent.com/13651296/93012185-5bae2a00-f59e-11ea-9ff1-64e64a3188fe.png)

**Comment by rxhanson** [comment] 2020-09-13 06:57
Closing this one out since I don't have plans to add it into Rectangle at this time.

**Closed by rxhanson** 2020-09-13 06:57 UTC
Labels: enhancement
