### ISSUE TITLE
Issue with Matlab 2018b

### ISSUE THREAD

**Issue by dslemusp** [rxhanson/Rectangle#397] opened 2021-03-02 11:32 UTC
- [x] This is a new bug that hasn't been documented in a closed issue or in the Readme.

macOS version: BigSur 11.2.2
Rectangle version: 0.43
Logs if applicable (In Rectangle menu, hold option, "View Logging..."): 

Matlab 2018b is very slow while using rectangle. Closing rectangle solves the issue. This has been reported in https://nl.mathworks.com/matlabcentral/answers/421446-r2018b-r2019a-runs-very-slow-on-macos-10-14 for rectangle as well.

A simple test is to try to set a breakpoint in the editor. It becomes really slow.

**Comment by rxhanson** [comment] 2021-03-02 11:40
Duplicate of https://github.com/rxhanson/Rectangle/issues/300?

**Comment by dslemusp** [comment] 2021-03-02 11:48
Yes!, Indeed that solved the issue. I guess I did a bad job browsing for "Matlab" in the issue browser.

**Closed** 2021-03-02 11:56 UTC
Labels: bug
