### ISSUE TITLE
Preferences window is displayed during autostart

### ISSUE THREAD

**Issue by rnurgaliyev-s11** [rxhanson/Rectangle#685] opened 2021-12-17 08:42 UTC
- [x] This is a new bug that hasn't been documented in a closed issue or in the Readme.

macOS version: 12.1
Rectangle version: 0.49
Logs if applicable (In Rectangle menu, hold option, "View Logging..."): Empty

If "Launch on login" is enabled, Rectangle will show the preferences window shortly after the system boots. For some reason, it does not happen if I just restart the rectangle.

**Comment by rxhanson** [comment] 2021-12-17 12:55
Duplicate of https://github.com/rxhanson/Rectangle/issues/579

**Closed** 2021-12-17 12:55 UTC
Labels: bug
