### ISSUE TITLE
Cycling between displays loses the selected application

### ISSUE THREAD

**Issue by JordanTranchina** [rxhanson/Rectangle#277] opened 2020-12-01 00:37 UTC
May be similar to issue #255 

Current Experience: Rectangle is not able to move the selected application/window when one of the other displays has a fullscreen app on it.
![Screen Shot 2020-11-30 at 6 35 28 PM](https://user-images.githubusercontent.com/41443492/100682074-d899a600-333a-11eb-9de0-29a7c6dc7c97.png) - Example of the fullscreen app.
I have two external displays + my macbook pro laptop.

Desired Experience: Rectangle would continue to move the app to a desktop or display aside from the one that is in fullscreen mode!

- [x ] This is a new bug that hasn't been documented in a closed issue or in the Readme.
macOS version: Catalina 10.15.17
Rectangle version: v0.38 (43)
Logs if applicable (In Rectangle menu, hold option, "View Logging..."): 
2020-11-30T18:29:58-06:00: AX sizing proposed: (1680.0, 991.0), result: (1680.0, 991.0)
2020-11-30T18:29:58-06:00: AX position proposed: (-1277.0, -1204.0), result: (-1277.0, -1204.0)
2020-11-30T18:29:58-06:00: AX sizing proposed: (1680.0, 991.0), result: (1680.0, 991.0)
2020-11-30T18:29:58-06:00: previousDisplay | display: (-1717.0, 1050.0, 2560.0, 1417.0), calculatedRect: (-1277.0, -1204.0, 1680.0, 991.0), resultRect: (-1277.0, -1204.0, 1680.0, 991.0), srcScreen: Built-in Retina Display, destScreen: VG2755-2K, resultScreen: VG2755-2K
2020-11-30T18:29:58-06:00: AX sizing proposed: (1680.0, 991.0), result: (1680.0, 991.0)
2020-11-30T18:29:58-06:00: AX position proposed: (1283.0, -1204.0), result: (1283.0, -1204.0)
2020-11-30T18:29:58-06:00: AX sizing proposed: (1680.0, 991.0), result: (1680.0, 991.0)
2020-11-30T18:29:58-06:00: previousDisplay | display: (843.0, 1050.0, 2560.0, 1417.0), calculatedRect: (1283.0, -1204.0, 1680.0, 991.0), resultRect: (1283.0, -1204.0, 1680.0, 991.0), srcScreen: VG2755-2K, destScreen: VG2755-2K, resultScreen: VG2755-2K
2020-11-30T18:29:59-06:00: Unable to obtain window id
2020-11-30T18:29:59-06:00: Unable to obtain window id
2020-11-30T18:29:59-06:00: Unable to obtain window id
2020-11-30T18:30:00-06:00: Unable to obtain window id
2020-11-30T18:30:00-06:00: Unable to obtain window id
2020-11-30T18:30:00-06:00: Unable to obtain window id
2020-11-30T18:30:00-06:00: Unable to obtain window id
2020-11-30T18:30:01-06:00: Unable to obtain window id
2020-11-30T18:30:01-06:00: Unable to obtain window id
2020-11-30T18:30:01-06:00: Unable to obtain window id
2020-11-30T18:30:01-06:00: Unable to obtain window id

**Comment by rxhanson** [comment] 2020-12-01 11:45
Thanks for reporting. A couple quick questions:

1. Is your expected behavior that moving a window to a display that has a fullscreen app(s) on it would skip that display and go to the next?
1. When you're trying to move a window to the display with fullscreen apps, what is happening to the window? Is it not moved at all? My expected behavior is that it would behave as mentioned in the issue you linked. The behavior can be a little different depending on if you are moving a window that is from the same app as the fullscreen one.

**Comment by JordanTranchina** [comment] 2020-12-03 04:07
1. Yes that is my desired behavior as you described.
2. It gets stuck on the other desktop on the monitor (still moved to the 2nd display but stuck on the first desktop of the 2nd display and not able to move back to the laptop or 1st display). The moving window is not in the same app as the fullscreen one.


Jordan Tranchina
MBA Candidate | Kellogg School of Management | Class of 2022
Website | LinkedIn | Schedule Call

**Comment by JordanTranchina** [comment] 2021-01-09 20:32
Hey @rxhanson,

Looks like this issue has been resolved in a recent build. When moving windows to a different display the display now shifts desktops to show the moved window, which is perfect!

Thank you 🥇 
Jordan

**Comment by rxhanson** [comment] 2021-01-09 21:04
Great! Thanks for reporting back. This one is pretty strange to me, as I actually haven't changed anything for it in recent releases and it's rather hit or miss if this works for users or not. It has always worked as intended for me since I put a fix in for it in the linked issue. 

I'm going to close this one out, but feel free to comment again or reopen if somehow it doesn't work for you at some point.

**Closed by rxhanson** 2021-01-09 21:04 UTC
Labels: bug
