### ISSUE TITLE
Left and Right half width not calculated correctly when dock hidden to left side

### ISSUE THREAD

**Issue by parthv21** [rxhanson/Rectangle#450] opened 2021-04-25 21:48 UTC
- [X] This is a new bug that hasn't been documented in a closed issue or in the Readme.

macOS version: 11.0.1
Rectangle version: 0.41 (46)

On dragging to the left edge of the screen, the correct fill area is shown but when actual resizing happens the width is not correct. For the right edge, even the fill area has incorrect width. Seems to be happening on an external monitor only. 

<img width="1915" alt="Screen Shot 2021-04-25 at 4 44 15 PM" src="https://user-images.githubusercontent.com/17941287/116010682-13e88a00-a5e6-11eb-9bf9-a5115e2729a7.png">

**Comment by rxhanson** [comment] 2021-04-26 07:56
Some windows have a minimum size, like the app store window. The Rectangle footprint window is the target size and there's no way to know ahead of time if the window will fit into the target size unless the app keeps track of resulting sizes for each window. I have no plans to add that functionality into Rectangle (it would be ambiguous and it's more straightforward to me to always show the target size).

For the fill area being incorrect width, can you send logs (hold option in the menu and select View logging). Performing a shortcut will give us logs for the proposed sizing, and that should match the target size.

**Comment by rxhanson** [comment] 2021-05-13 23:47
Closing this one out since it sounds like the issue is just that certain windows have a minimum size. Feel free to comment or reopen if that's not the case.

**Closed by rxhanson** 2021-05-13 23:47 UTC
Labels: bug
