### ISSUE TITLE
Inconsistent shortcuts

### ISSUE THREAD

**Issue by mcdickenson** [rxhanson/Rectangle#207] opened 2020-08-26 21:35 UTC
macOS version: 10.15.6
Rectangle version: 0.31

I have Rectangle installed on two Macbooks (same model) with the same OS and app version, but the shortcuts are different. For example on one of them "bottom right" is Ctrl+Option+K and on the other it's Ctrl+Shift+Cmd+RightArrow. I prefer the first set of shortcuts but haven't found a way to get that behavior on the second machine.

**Comment by rxhanson** [comment] 2020-08-26 21:46
Looks like on one of your machines you selected the recommended shortcuts on first launch, and on the other you selected spectacle shortcuts. Changing this after first launch is an open issue here: https://github.com/rxhanson/Rectangle/issues/141, and you can follow the instructions there to get what you want. Ctrl+Option+K for bottom right is in the "recommended" Rectangle defaults.

Closing this as a duplicate of https://github.com/rxhanson/Rectangle/issues/141

**Closed by rxhanson** 2020-08-26 21:46 UTC
Labels: bug
