### ISSUE TITLE
Rectangle causes ThinkOrSwim App to hang

### ISSUE THREAD

**Issue by rno1d** [rxhanson/Rectangle#259] opened 2020-11-06 04:42 UTC
Whenever `Rectangle` is running and you try to Scroll or Resize a window in [ThinkOrSwim](https://www.tdameritrade.com/tools-and-platforms/thinkorswim/desktop/download.page), Rectangle causes it to hang and results in a spinning BeachBall.

I thought doing something like `Rectangle Menu` >  `Ignore ThinkOrSwim` would fix the issue but it doesn't.

From the screen recording, notice how I try to scroll horizontally, then the App hangs. 

When I bring up the Activity Monitor, you can see **ThinkOrSwim  Memory** usage growing ridiculously large, and continues to get large until I Force Quit.

macOS version: **10.15.2 (Catalina)**
Rectangle version: **0.37 (42)**
logs (In Rectangle menu, hold option, "View Logging..."): **Empty**

![Rectangle-ToS](https://user-images.githubusercontent.com/11546210/98324953-a5722a00-1fbb-11eb-9ec8-4002930ca00e.gif)

**Comment by rxhanson** [comment] 2020-11-06 07:46
Duplicate of https://github.com/rxhanson/Rectangle/issues/231

**Closed by rxhanson** 2020-11-06 07:46 UTC
Labels: bug
