### ISSUE TITLE
How to describe Mac OS bug?

### ISSUE THREAD

**Issue by DrRob** [rxhanson/Rectangle#165] opened 2020-05-29 15:20 UTC
How should I describe the "_Window moving/resizing appears animated/smooth instead of quick, and windows don't end up where you expect_" bug in the Mac OS feedback form?  Is it specific to Rectangle or more general?  If the latter, how should I describe it without reference to Rectangle?

e.g. I guess it might be something like this: "When Accessibility utilities try to resize/reposition a window, for some applications such as Google Chrome this results in the window size/position animating and not ending up in the size/position requested.  See: https://github.com/rxhanson/Rectangle#window-movingresizing-appears-animatedsmooth-instead-of-quick-and-windows-dont-end-up-where-you-expect"

It's quite a showstopper for me as it makes Rectangle useless on Google Chrome windows.

I'm using v0.25.1, but the delay is annoying.

**Comment by rxhanson** [comment] 2020-05-29 18:24
Good question. Your proposed text looks good to me. If you are aware of what's causing it - if it's any of the triggers that I've listed then it might help to add that as well.

If you wanted to reference issues where this was reported for Rectangle, you can reference these:
https://github.com/rxhanson/Rectangle/issues/94
https://github.com/rxhanson/Rectangle/issues/29
https://github.com/rxhanson/Rectangle/issues/15

I think the main thing will be that the folks Apple side will correlate all of the bugs reported for this to the same issue, and the text you have should be enough for that.

Thanks!

**Comment by DrRob** [comment] 2020-05-30 20:43
I don't know if this is relevant but I was previously using Spectacle and this problem starting happening there.  I went to check for updates and discovered that Spectacle is now unmaintained, so looked for an alternative, and that's how I came across Rectangle.

The strange thing is it's only affecting my work Macbook (a 2018 model) - my home Macbook (a late 2013 model, still using Spectacle) isn't having the problem.

I tried unticking all the other apps that have Accessibility permissions and that made no difference.

**Comment by rxhanson** [comment] 2020-05-30 21:13
Unfortunately, I'm in the dark as much as you are on what could trigger this. The fact that some users experience it when an external monitor is connected means it's maybe not necessarily directly tied to accessibility applications, but just to some level of macOS infrastructure that handles window movement. 

This happening in Spectacle (and Rectangle) is just exposing the problem, not creating it. I was able to reproduce it with Magnet as well, using both the macOS on-screen keyboard and a Russian app, Punto switcher.

I don't know how far you're willing to go on this, but you could try making a new user on your mac and just see if fresh settings from a user level make a difference. Of course, there's always the nuclear option of backing up your mac and doing a straight up fresh install but I don't blame you if you don't want to do that. 

It's just... I have no idea if Apple will fix this. It's a hard case to make to say "Hey Apple, I have a problem using a 3rd party tool that uses APIs you no longer allow in the mac app store, and that dev claims it's your bug".  I genuinely think it would take a really large number of people filing the issue for Apple to even think about it. Since Magnet exhibits the issue as well, maybe something might come of it?

**Comment by DrRob** [comment] 2020-06-02 10:34
I just made a discovery - if I enable "Reduce motion" in the "Display" section of the "Accessibility" system preferences, the problem goes away (with Rectangle 0.30).

Caveat: I've only been testing it for about a minute.

**Comment by rxhanson** [comment] 2020-06-02 19:22
Awesome! That doesn't fix it for me when I reproduce the issue using the on-screen keyboard. Let me know if it did fix the issue for you and I'll add it as something to try in the Readme.

**Comment by DrRob** [comment] 2020-06-03 08:56
I've been using it like this for a day with no issues.  It's really nice
having fast window positioning back, and I don't miss the animated window
resizing/repositioning at all.

It's not a perfect fix though because I miss the transition effects in
other places - a four-finger swipe left/right to select a Space now does a
fade instead of scroll, and a four-finger swipe up/down to expose all
windows also does a fade, neither of which are as intuitive.

Curiously, minimising a window still does the "genie" animation into the
Dock.

**Comment by rxhanson** [comment] 2020-06-03 09:45
Thanks for reporting back with the details. I'll go ahead and update the Readme with this. 

Weird that macOS wouldn't automatically change the genie setting for you if you select Reduce motion - it does similar automatic setting changes for other settings.

**Comment by DrRob** [comment] 2020-06-04 05:57
I updated MacOS from 10.15.3 to 10.15.4 and then 10.15.5 last night, and just for fun, I turned off the "Reduce motion" setting to see what happens, and now Rectangle resizes/repositions Chrome windows with no problems (and no animation either).  Transitions are back on for four-finger swipes (I checked).

So now I don't know if Apple fixed something in one of the updates or whether just turning "Reduce motion" on and off again is enough to do it.

¯\_(ツ)_/¯

**Comment by rayshan** [comment] 2020-06-04 18:16
Thank you @DrRob. Having issue with Spectacle and coming over to Rectangle is exactly what I went through too.

**Comment by rayshan** [comment] 2020-06-06 19:50
Unfortunately upgrading to 10.15.5 and turning reduced motion on / off don't fully solve the problem. Sometimes, but not always, the resize is still inconsistent and the animation is still shown.

**Comment by jakob-stoeck** [comment] 2020-07-21 09:01
I’m having the same issue since Spectacle and now Rectangle on different MacBooks new and old over all macOS versions of the last years.

But I always had "Reduce motion" enabled. The problem occurs nevertheless.

Still I cannot pin it down, but it seems to me it happens more often when I’m using Slack on Chrome.

**Comment by Johnny-Wish** [comment] 2020-09-27 23:34
I  have been experiencing these issue for a couple of months. 
However, this issue seems to be fixed in macOS 10.15.7. 
After updating to this version today, the issue no longer occurs to my MacBook.

**Comment by ibash** [comment] 2020-10-22 17:53
+1 to the "spectacle is broken, let's try rectangle" train.


Is this the same issue you all are seeing? [screen recording](https://notion-c23db2345ad3.intercom-attachments-3.com/i/o/253109166/c90f906f7ddff271a74c166f/Screen+Recording+2020-10-06+at+10.18.55+AM.mov)

For me this affects two desktop apps in particular:
1. Whatsapp desktop
2. Notion desktop

Both are electron apps so I did some digging to see if I could figure it out.

I found that the bug reproduced even if I removed most of the JS code running in those apps.
But, if I used electron from my machine the bug went away.

By "used electron from my machine" I mean:

```
npm install -g electron
electron /Applications/Notion.app/Contents/Resources/app.asar
```

I didn't match chrome versions, so think this could be a chrome related bug.

**Comment by jakob-stoeck** [comment] 2020-10-26 03:02
Yes @ibash, that’s the one. Didn’t happen to me anymore since perhaps three months anymore. Maybe a macOS update? I’m on 10.15.7.

**Comment by ibash** [comment] 2020-10-26 06:18
I'm also on 10.15.7 -- curious if you're able to reproduce it by using the [notion](https://www.notion.so/desktop) or WhatsApp desktop apps (don't even need to login).

If you can then I think it's a chrome issue, if not then I have hope :)

**Comment by ibash** [comment] 2020-10-27 06:56
started looking at this on the rectangle / chrome side

In rectangle windows are positioned like:
```swift
func setRectOf(_ rect: CGRect) {
    set(size: rect.size)
    set(position: rect.origin)
    set(size: rect.size)
}
```

But for notion / whatsapp the size and position setting are not instant, they're animated and there's a delay.
That's important because the window will refuse to move to a position off screen.

e.g.
1. app window is in the bottom right corner of the screen
2. attempt to maximize the window

In that case the first `set(size: rect.size)` will not actually expand size, because it would force the window to go beyond the edge of the screen.

Setting size then position, then size again seems to be a workaround to this, but because the window is slow to update it doesn't work in this case (since the position doesn't not update instantly).

e.g. if you set a delay on the second `set(size: rect.size)` then the code _does_ work (albeit delayed).

Accessibility apis are still new to me, but read briefly that it's handled by the target process, right?

**Comment by rxhanson** [comment] 2020-10-27 07:32
@ibash This is the premise of v0.25.1 - changing the app to asynchronously wait a preset delayed time before attempting to perform each window dimension change. I left the branch `animation-delay` up that v0.25.1 was built off of if you want to look at it or tailor it to do what you want. I'm not going to roll that asynchronous behavior into the current Rectangle release, though.

The reason why this issue is the only one that's left open regarding this behavior is because it really is a bug that should be fixed macOS side (or in the specific apps that exhibit this behavior).

**Comment by ibash** [comment] 2020-11-01 19:56
I've discovered a workaround, but I don't understand it.
Can someone else who can reproduce the bug try this workaround?

### Steps
First ensure you can reproduce the bug

1. Download notion desktop app and install it
2. Open the app
3. Move the app with rectangle

Expected: You should be able to reproduce the bug in this issue

Then attempt the fix:
1. Quit the app
2. Open `/Applications/Notion.app/Contents/Info.plist` in xcode for editing (I'm using vim, but should be the same)
3. Change the bundle id `notion.id` to something else (e.g. `foo.id`)
4. Save Info.plist
5. Open the app
6. Move the app with rectangle

Expected: The bug no longer reproduces

If you change the bundle id back to `notion.id` then it reproduces again.

---

For people that can reproduce the bug with other apps (not notion), can you try swapping the bundle id to see if it fixes it for you?

---

I have two guesses:
1. The bundle id is used in the app to load a framework or some other code that triggers the bug
2. The bundle id is associated with a specific setting in macos that triggers the bug (if anyone has ideas of places to check, I'm all ears, I tried an `lsregister -u` and `tccutil reset` but neither changed anything).

**Comment by rxhanson** [comment] 2020-12-07 20:25
This is now fixed in Rectangle, [v0.40 ](https://github.com/rxhanson/Rectangle/releases/tag/v0.40)(currently marked as pre-release).

**Closed by rxhanson** 2020-12-07 20:25 UTC
Labels: documentation

**Comment by davidawad** [comment] 2022-11-17 20:52
I just started experiencing this issue on google chrome and I have no idea why it's happening.

**Comment by yoshitamagoshi** [comment] 2022-12-02 03:48
Also experiencing this after upgrading to macOS Ventura on Mac Studio M1 Ultra.

**Comment by mrcola91** [comment] 2022-12-05 20:17
Also just noticed that Rectangle is inoperable for Chrome after updating to Ventura

**Comment by rxhanson** [comment] 2022-12-05 20:55
Chrome issue: https://github.com/rxhanson/Rectangle/issues/912

**Comment by yoshitamagoshi** [comment] 2022-12-05 21:09
Fwiw, after forcing Chrome to update it resolved the issue for me on Mac Studio w/ Ventura.
