### ISSUE TITLE
Center two thirds?

### ISSUE THREAD

**Issue by acousticbiker** [rxhanson/Rectangle#187] opened 2020-07-10 22:30 UTC
Hi there, great app - thanks for providing an improvement to Spectacle! I saw that you are not accepting new feature requests but thought I'd throw this one in there because it seems to be a missing variation of existing options. Would you consider adding a 'Center two thirds' option? I currently use left or right two thirds and then center to achieve this but one click/keystroke would be nice.

**Comment by rxhanson** [comment] 2020-07-10 22:43
Duplicate of https://github.com/rxhanson/Rectangle/issues/148 and https://github.com/rxhanson/Rectangle/issues/52

Maybe this can be explicitly added in when the UI is updated to handle more actions.

**Closed by rxhanson** 2020-07-10 22:43 UTC
Labels: enhancement

**Comment by brakende** [comment] 2020-11-16 06:44
This would be very much appreciated! On my 34', some apps are better in center 2/3ds.

**Comment by sinharaksh1t** [comment] 2023-10-24 01:13
> > Execute the following terminal commands to modify the Almost Maximize ratio.
> > `defaults write com.knollsoft.Rectangle almostMaximizeHeight -float 1`
> > `defaults write com.knollsoft.Rectangle almostMaximizeWidth -float 0.66`

Exactly what I was looking for! Thanks for the workaround!

**Comment by folsze** [comment] 2023-11-06 19:18
Do note that you have to restart reactangle for it to take effect! 
(restarting of any previously active apps not necessary)
