### ISSUE TITLE
Rectangle hangs and consumes excessive CPU, have to force quit

### ISSUE THREAD

**Issue by davethetenor** [rxhanson/Rectangle#309] opened 2020-12-24 14:51 UTC
Rectangle will occasionally hang and consume a large amount of CPU (10-30%). To recover I have to Force Quit and restart the app, which I have to do about twice a day on average. It seems to happen most often when I'm on a Zoom call, but I don't know if it's directly related or not - I'm on a *lot* of Zoom calls these days. :)

![Screen Shot 2020-12-22 at 8 40 20 AM](https://user-images.githubusercontent.com/76563247/103095097-a1768780-45bc-11eb-8841-99365c518405.png)

macOS version: 10.15.7
Rectangle version: 0.38 (43)
Logs if applicable (In Rectangle menu, hold option, "View Logging..."): [Since this makes Rectangle unresponsive I can't collect the log. If it's stored on disk and you get me the path I could grab it directly next time it happens...]

**Comment by rxhanson** [comment] 2020-12-25 14:14
Thanks for reporting. Off the top of my head, there's really only one part of the code that would be capable of increasing CPU, and I think you've hit a pretty rare scenario that would cause this to increase to this degree. The logging mechanism in Rectangle doesn't write to disk, it just outputs to the log viewing window when it is open. You could open that viewer window when the app starts (at least before it hangs) and potentially get some useful logs out of it. I have a fix in mind for the next release regardless, but if it doesn't pan out then logs will be useful.

As a workaround for the time being, you can uncheck the box for snap windows by dragging in the prefs window (this is the area of code where I'll be putting in a fix).

**Comment by davethetenor** [comment] 2020-12-26 17:56
Awesome, thanks for responding! I just saw you released v0.40 - does that include this fix, or should I still try the workaround? Happy to leave the option on and report back if you’d like.

-David

**Comment by rxhanson** [comment] 2020-12-27 09:10
v0.40 does not include the fix, but it will be added into v0.41. I'll comment here when that gets released.

**Comment by rxhanson** [comment] 2020-12-30 21:59
v0.41 is now released:
https://github.com/rxhanson/Rectangle/releases/tag/v0.41

If you still have the issue, try and see if you can get anything from the log window (open it before you think you'll hit problems by holding option in the status bar menu and selecting "View Logging"). If you can't get anything from the logs since the app hangs at that point, then I'll change some things up so it will log to a file. I haven't had to log to a file yet since this is the first issue I've come across that might actually require it.

Thanks!

**Comment by lcasale** [comment] 2021-01-06 21:33
Hello @rxhanson - I'm experiencing this issue in Catalina with v0.41. I'll try to capture some logs when it happens again

**Comment by Werevolk** [comment] 2021-01-12 12:52
v0.41 on Big Sur - same bug ( Occasional freezes with huge CPU usage.

**Comment by rxhanson** [comment] 2021-01-12 15:42
Thanks for the logs, all! Unfortunately, I'll have to add in more logging to get to the bottom of it.

@Werevolk, on Big Sur, if you open Console.app and go to Spin Reports, is there one for Rectangle?

**Comment by Werevolk** [comment] 2021-01-12 18:23
@rxhanson Spin Report section is empty.

**Comment by rxhanson** [comment] 2021-01-13 21:16
I've given this some more thought, and all three of the log screenshots here point to different places. It could be beneficial to add more detailed logging, and log to file instead of in memory, but it would be way more efficient to get to the bottom of it if someone is up for profiling this. 

I've outlined the steps to use the profiler here:
https://github.com/rxhanson/Rectangle/wiki/Using-the-profiler

Let me know if anyone's up for it!

**Comment by rxhanson** [comment] 2021-01-20 08:21
I think this should now be fixed in v0.42:
https://github.com/rxhanson/Rectangle/releases/tag/v0.42

Let me know if anyone has a chance to try it out.

**Comment by lcasale** [comment] 2021-01-21 21:32
Hey @rxhanson - it froze up again on me with v0.42. I'm going to profile again on the new version and send those traces your way.

**Comment by borwickatuw** [comment] 2021-01-21 22:24
FYI Rectangle has been freezing for me a couple of times per day but it hasn't yet so far with v0.42!

**Comment by lcasale** [comment] 2021-02-02 13:41
It's been solid since the initial freeze going on almost 2 weeks now

**Comment by borwickatuw** [comment] 2021-02-02 16:03
> It's been solid since the initial freeze going on almost 2 weeks now

agreed--I haven't seen it freeze either!

**Comment by rxhanson** [comment] 2021-02-02 18:20
Great! Thanks for reporting back (and huge thanks to @lcasale for the initial profile that got us to this point!)

I will leave this issue open a little longer since @lcasale had that initial freeze. If anyone can reproduce a freeze and is willing to profile it, definitely let me know.

**Comment by rxhanson** [comment] 2021-03-07 15:35
Closing this one out. Feel free to comment if anyone experiences this again.

**Closed by rxhanson** 2021-03-07 15:35 UTC
Labels: bug
