### ISSUE TITLE
Window interaction with the Dock on external display

### ISSUE THREAD

**Issue by andsimakov** [rxhanson/Rectangle#183] opened 2020-06-26 07:22 UTC
macOS version: 10.15.5
Rectangle version: 0.30(35)
logs (In Rectangle menu, hold option, "View Logging..."): —

Macbook Pro 15 2017. When I use Rectangle app on the internal display with the Dock there Full Screen action expands a window taking into account the Dock — just stops above it. When I attract the Dock on the external display and do the same all windows are being maximized down to bottom display edge, under the Dock. I have to drag bottom edge of each window to put it above the Dock because sometimes it is critical for some webpage elements or status bars of apps.

**Comment by rxhanson** [comment] 2020-06-27 22:14
Duplicate of https://github.com/rxhanson/Rectangle/issues/166

> This is actually a macOS issue where the available screen reported via the Accessibility API that Rectangle uses is not properly updated when the dock is moved. Unfortunately, there's not an elegant way that I'm aware of to fix this from a 3rd party perspective. Have you tried any other window manager apps that don't exhibit this behavior? I know it was reported as an issue for Spectacle, without solution.

If you've seen any other window manager apps that don't have this issue, feel free to reopen or comment further and I'll dig into this again.

**Closed by rxhanson** 2020-06-27 22:14 UTC

**Comment by andsimakov** [comment] 2020-06-30 11:04
OK, clear. I partially fixed it for me by dragging that white menu bar in Display preferences to the external display. It works well with it.
