### ISSUE TITLE
no mountable filesystems

### ISSUE THREAD

**Issue by dmaglio** [rxhanson/Rectangle#1385] opened 2024-05-08 18:05 UTC
macOS version: 14.4.1 on Mac Mini M1
Rectangle version: every version

if i download any version of rectangle, cannot mount disk image. same result via brew install --cask rectangle

**Comment by rxhanson** [comment] 2024-05-09 00:50
Thanks for reporting. I can't reproduce it and you're the first to report this. I suspect you have something unusual about your setup? If you just updated macOS, try rebooting one more time.

**Comment by rxhanson** [comment] 2024-06-04 04:46
Closing, but feel free to reopen if this is still applicable.

**Closed by rxhanson** 2024-06-04 04:46 UTC
Labels: bug
