### ISSUE TITLE
Doesn't launch on startup

### ISSUE THREAD

**Issue by najiglass** [rxhanson/Rectangle#48] opened 2019-12-08 21:12 UTC
With rectangle 0.12 on Mac OS 10.14.6, rectangle is configured to launch on startup, but it doesn't, I need to manually open the app every time I restart.

**Comment by rxhanson** [comment] 2019-12-09 06:14
This is a duplicate of https://github.com/rxhanson/Rectangle/issues/17. I'll leave this one open until I make a change in the next release for it.

**Comment by rxhanson** [comment] 2019-12-10 15:09
This should be patched up in https://github.com/rxhanson/Rectangle/releases/tag/v0.13.

Give that a try and let me know if you still have issues.

**Comment by najiglass** [comment] 2019-12-10 16:07
Wonderful, thank you, will let you know if it doesn’t work.

**Comment by rxhanson** [comment] 2019-12-20 14:35
I'm guessing this is working fine in v0.13. These same changes are included in 0.14 (which will be an official release). 

Feel free to reopen if there's still problems in v0.13 or v0.14.

**Comment by najiglass** [comment] 2019-12-20 14:35
It does thank you!

**Closed by rxhanson** 2019-12-20 14:35 UTC
