### ISSUE TITLE
Rectangle can not resize window once fully-maximized

### ISSUE THREAD

**Issue by mozfreddyb** [rxhanson/Rectangle#816] opened 2022-05-12 11:23 UTC
- [x] This is a new bug that hasn't been documented in a closed issue or in the Readme.

macOS version: Monterey 12.3.1
Rectangle version: 0.5.6 (latest)
Logs if applicable (In Rectangle menu, hold option, "View Logging..."): 

It looks like a windows once fully maximized with the green maximize button can not be resized with Rectangle.
STR:
- Maximize a window (click the green button in the top right)
- Use any Rectangle short-cut or click an option from the dropdown (e.g., Cmd+Option+Left to use only the left half)

What should happen:
- Rectangle should resize the window accordingly

What actually happens:
- Nothing.

**Comment by rxhanson** [comment] 2022-05-19 00:31
Thanks @gothic-bum! Closing this one out, since this is expected behavior. Feel free to comment further if things are still unclear.

**Closed by rxhanson** 2022-05-19 00:31 UTC
Labels: bug
