### ISSUE TITLE
Unable to move FaceTime between screens

### ISSUE THREAD

**Issue by Leland** [rxhanson/Rectangle#445] opened 2021-04-16 17:24 UTC
- [x] This is a new bug that hasn't been documented in a closed issue or in the Readme.

macOS version: 10.15.7 and 11.2.3
Rectangle version: v0.45 (50)
Logs if applicable (In Rectangle menu, hold option, "View Logging..."): 

This is the result of first using Hotkeys to move a Facetime window _to_ my main laptop, and then _back_ to my external display. Visually, nothing happened - the window stayed put. The Facetime window size is quite small - I can drag it manually to my laptop screen without issues.

```
2021-04-16T13:22:44-04:00: AX sizing proposed: (652.0, 585.0), result: (652.0, 585.0)
2021-04-16T13:22:44-04:00: AX position proposed: (570.0, 279.0), result: (1792.0, 279.0)
2021-04-16T13:22:44-04:00: AX sizing proposed: (652.0, 585.0), result: (652.0, 585.0)
2021-04-16T13:22:44-04:00: AX sizing proposed: (652.0, 585.0), result: (652.0, 585.0)
2021-04-16T13:22:44-04:00: AX position proposed: (1140.0, 279.0), result: (1792.0, 279.0)
2021-04-16T13:22:44-04:00: AX sizing proposed: (652.0, 585.0), result: (652.0, 585.0)
2021-04-16T13:22:44-04:00: previousDisplay | display: (0.0, 0.0, 1792.0, 1097.0), calculatedRect: (570.0, 279.0, 652.0, 585.0), resultRect: (1792.0, 279.0, 652.0, 585.0), srcScreen: LG HDR 4K, destScreen: Built-in Retina Display, resultScreen: LG HDR 4K
2021-04-16T13:22:47-04:00: AX sizing proposed: (652.0, 585.0), result: (652.0, 585.0)
2021-04-16T13:22:47-04:00: AX position proposed: (570.0, 279.0), result: (1792.0, 279.0)
2021-04-16T13:22:47-04:00: AX sizing proposed: (652.0, 585.0), result: (652.0, 585.0)
2021-04-16T13:22:47-04:00: AX sizing proposed: (652.0, 585.0), result: (652.0, 585.0)
2021-04-16T13:22:47-04:00: AX position proposed: (1140.0, 279.0), result: (1792.0, 279.0)
2021-04-16T13:22:47-04:00: AX sizing proposed: (652.0, 585.0), result: (652.0, 585.0)
2021-04-16T13:22:47-04:00: nextDisplay | display: (0.0, 0.0, 1792.0, 1097.0), calculatedRect: (570.0, 279.0, 652.0, 585.0), resultRect: (1792.0, 279.0, 652.0, 585.0), srcScreen: LG HDR 4K, destScreen: Built-in Retina Display, resultScreen: LG HDR 4K
```

**Comment by rxhanson** [comment] 2021-04-21 19:20
Apologies for the delay on this one. I'm currently without an external display and getting ready to move, so I don't have an easy way to test it out. I'll post back when I get a chance to test it out.

**Comment by rxhanson** [comment] 2021-05-13 23:57
I was able to reproduce this, but unfortunately it looks like there's nothing that can be done Rectangle side so I'm going to close this issue. Apple's API is just not putting the window where Rectangle tells it to go.

Based on prior experience, I don't think it's something that Apple will bother fixing, so I don't think it's worth filing an issue with Apple. 

Thanks for reporting it here, though!

**Closed by rxhanson** 2021-05-13 23:57 UTC
Labels: bug
