### ISSUE TITLE
Rectangle seems to severely clash with Adobe Illustrator

### ISSUE THREAD

**Issue by vektorgarten** [rxhanson/Rectangle#1356] opened 2024-04-04 09:03 UTC
- [ ] This is a new bug that hasn't been documented in a closed issue or in the Readme.
I am a regular in the Adobe Community forums. I am not using Sonoma and I am not interested in even using this app. But others are doing so and they have longstanding inexplicable issues and then they post to the Adobe Community and we have to solve the issues. So just today someone discovered Rectangle to be making Adobe Illustrator unusable.

You can find out about it here: https://community.adobe.com/t5/illustrator-discussions/illustrator-is-unusable-crashes-when-opening-any-preferences-or-document-settings/m-p/14534034#M403442

macOS version: Sonoma 14.4.1
Rectangle version: I do not know
Logs if applicable (In Rectangle menu, hold option, "View Logging..."):

**Comment by rxhanson** [comment] 2024-04-05 04:44
Thanks for the heads up. I posted a comment on that thread and will update Rectangle to account for Illustrator, if necessary.

**Comment by rxhanson** [comment] 2024-04-30 03:05
Ignoring Illustrator or After Effects using the menu bar menu in Rectangle should fix the issue. In the latest version of Rectangle, users will be notified to ignore those apps if they are running when Rectangle starts. Closing this one out. Thanks again!

**Closed by rxhanson** 2024-04-30 03:05 UTC
Labels: bug

**Comment by JCKFTZY** [comment] 2025-05-06 21:54
Hi, I'm seeing the same issue.  Adobe Illustrator 2024 (v28.5.0) hangs when Rectangle is running in the background on macOS 15.4.1 (Sonoma).

The hang occurs when Illustrator’s UI is accessed via the Accessibility API, which Rectangle relies on. According to crash logs, Illustrator’s main thread becomes unresponsive inside:

NSAccessibilityElement → accessibilityAttributeValue → getAttributeValue:forObject:

"Ignoring" in Rectangle solved the issue, but it took me a long time to figure out Rectangle was causing it! 

I realize this is probably an Illustrator bug (Adobe’s side), but since Rectangle is the reproducible trigger, I wanted to share

**Comment by rxhanson** [comment] 2025-05-07 05:08
@JCKFTZY Thanks for this - I'm assuming you did not get a notification within Rectangle to ignore Illustrator?

**Comment by JCKFTZY** [comment] 2025-05-07 17:23
@rxhanson there's a chance I missed it, if it only shows a notification once upon install, but I don't think I saw one... I have Rectangle open on startup but even when I close and reopen (while illustrator is running) it I don't see a notification.
