### ISSUE TITLE
Message app not responding to Rectangle shortcuts

### ISSUE THREAD

**Issue by jmertic** [rxhanson/Rectangle#842] opened 2022-06-30 21:04 UTC
- [x] This is a new bug that hasn't been documented in a closed issue or in the Readme.

macOS version: 12.4
Rectangle version: 0.57
Logs if applicable (In Rectangle menu, hold option, "View Logging..."): None

Every other app I can use the keyboard shortcuts to move windows around with Rectangle...but Messages. This used to work about a month ago but is not working now. I can move the Messages window around using the options in the menu.

**Comment by rxhanson** [comment] 2022-07-01 02:20
Thanks for reporting. Unfortunately, this happens when an app (messages in this case) doesn't respond to the accessibility API in macOS for moving/resizing windows, and it's not something that can be handled in Rectangle. Typically, it's fixed by just restarting the app that's not responding.

**Comment by jmertic** [comment] 2022-07-01 11:25
Thanks @rxhanson. Tried restarting and the same deal - not sure if there is somewhere I could check for responding to the Accessibility API.

Note it's only the keyboard shortcuts that don't respond; if I do the resizing via the menu bar icon it works perfectly.

**Comment by rxhanson** [comment] 2022-08-13 18:44
Doing some housekeeping and closing out issues. Closing this one since there's not really anything that can be done from Rectangle's side here and I can't reproduce it. Feel free to comment further if there's any updates.

**Closed by rxhanson** 2022-08-13 18:44 UTC
Labels: bug
